*   buildrpm messages have a prefix to make them easier to spot *   Fixed buildrpm bug where --copy-tarball option swallowed its successor *   Fixed buildrpm bug which got package name and version from the     pre-checkout configure.in *   Fixed stupid buildrpm bug in copyfile.

diff --git a/buildrpm b/buildrpm
--- a/buildrpm
+++ b/buildrpm
@@ -17,6 +17,11 @@ fatal ()
     exit 1
 }
 
+message ()
+{
+    echo "buildrpm: $*"
+}
+
 usage ()
 {
     echo "Usage: $0 [--force] [--cvs-update] [--build-host=host] [--rpm-destination=[host:]dir]"
@@ -42,7 +47,7 @@ while [ $# -gt 0 ]; do
     --cvs-update=*) CVSTAG=${1#*=} ;;
     -d|--rpm-destination) RPMDEST=$2 ; shift ;;
     --rpm-destination=*) RPMDEST=${1#*=} ;;
-    -t|--copy-tarball) boolopt COPYTARBALL yes ; shift ;;
+    -t|--copy-tarball) boolopt COPYTARBALL yes ;;
     --copy-tarball=*) boolopt COPYTARBALL $1 ;;
     *) usage ;;
     esac
@@ -57,7 +62,7 @@ done
 
 case "$BUILDHOST" in
 ""|"$LOCALHOST"|localhost)
-    echo "Building on local host ($LOCALHOST)"
+    message "Building on local host ($LOCALHOST)"
     if [ -z "$__BUILDRPM_LOGGED" ]; then
 	export __BUILDRPM_LOGGED=yes
 	exec ./buildrpm \
@@ -69,7 +74,7 @@ case "$BUILDHOST" in
     fi
     ;;
 *)
-    echo "Building on remote host \"$BUILDHOST\""
+    message "Building on remote host \"$BUILDHOST\""
     (
 	set -x
 	ssh $BUILDHOST "cd $PWD && \
@@ -80,6 +85,62 @@ case "$BUILDHOST" in
 		--copy-tarball=$COPYTARBALL"
     ) 2>&1 | tee build.$BUILDHOST.log
     exit
+    ;;
+esac
+
+RPMDIR=rpm.d
+if [ -x /usr/bin/rpmbuild ] ; then
+    RPMBUILD=rpmbuild
+else
+    RPMBUILD=rpm
+fi
+
+# Calculate a string which identifies the Linux distro
+DISTRO=
+if [ -f /etc/redhat-release ]; then
+    DISTRO=rh$(sed -e 's|.*release[ \t]\+\([^ \t]\+\).*|\1|g' < /etc/redhat-release)
+fi
+
+#echo RPMDIR=$RPMDIR
+#echo DISTRO=$DISTRO
+#echo RPMBUILD=$RPMBUILD
+#echo CVSIGNORES=\"$CVSIGNORES\"
+#echo FORCE=$FORCE
+#exit 1
+
+case "$CVSTAG" in
+"")
+    # Do nothing
+    ;;
+HEAD)
+    message "Checking for locally changed files"
+
+    CVSIGNORES_RE=$(echo $CVSIGNORES | sed -e 's/^[ \t]*/^(/g'  -e 's/[ \t]*$/)$/g' -e 's/[ \t][ \t]*/|/g')
+
+    CHANGED=$(cvs -nq up | awk '$1~/^[MC]$/ && $2!~/'$CVSIGNORES_RE'/{print $2}')
+    [ -z "$CHANGED" ] || \
+    	fatal "These files are changed in this work area: $CHANGED"
+    message "Updating files from CVS"
+    (
+    	set -x
+    	cvs -q up || exit 1
+    ) || exit 1
+    ;;
+*)
+    message "Checking out a new directory with tag $CVSTAG"
+
+    BUILDDIR=build.d
+    [ -d $BUILDDIR ] && rm -rf $BUILDDIR
+    ROOT=$(cat CVS/Root)
+    REPOS=$(cat CVS/Repository)
+
+    message "Updating files from CVS"
+    (
+    	set -x
+	cvs -d $ROOT co -r$CVSTAG -d $BUILDDIR $REPOS || exit 1
+    ) || fatal "Can't check out from CVS"
+    [ -z "$RPMDEST" ] && RPMDEST=$(/bin/pwd)
+    cd $BUILDDIR || fatal "Checkout succeeded but no directory"
     ;;
 esac
 
@@ -94,7 +155,6 @@ else
 fi
 
 SPECFILE=${PACKAGE}.spec
-RPMDIR=rpm.d
 
 TARBALL=`awk '/^Source:/{print $2}' < $SPECFILE.in`
 case "$TARBALL" in
@@ -104,66 +164,13 @@ case "$TARBALL" in
 *) fatal "cannot calculate tarball extension from $SPECFILE" ;;
 esac
 
-if [ -x /usr/bin/rpmbuild ] ; then
-    RPMBUILD=rpmbuild
-else
-    RPMBUILD=rpm
-fi
-
-# Calculate a string which identifies the Linux distro
-DISTRO=
-if [ -f /etc/redhat-release ]; then
-    DISTRO=rh$(sed -e 's|.*release[ \t]\+\([^ \t]\+\).*|\1|g' < /etc/redhat-release)
-fi
-
+#echo TARBALL=$TARBALL
 #echo PACKAGE=$PACKAGE
 #echo VERSION=$VERSION
-#echo TARBALL=$TARBALL
-#echo RPMDIR=$RPMDIR
-#echo DISTRO=$DISTRO
-#echo RPMBUILD=$RPMBUILD
-#echo CVSIGNORES=\"$CVSIGNORES\"
-#echo FORCE=$FORCE
 #exit 1
 
-case "$CVSTAG" in
-"")
-    # Do nothing
-    ;;
-HEAD)
-    echo "Checking for locally changed files"
-
-    CVSIGNORES_RE=$(echo $CVSIGNORES | sed -e 's/^[ \t]*/^(/g'  -e 's/[ \t]*$/)$/g' -e 's/[ \t][ \t]*/|/g')
-
-    CHANGED=$(cvs -nq up | awk '$1~/^[MC]$/ && $2!~/'$CVSIGNORES_RE'/{print $2}')
-    [ -z "$CHANGED" ] || \
-    	fatal "These files are changed in this work area: $CHANGED"
-    echo "Updating files from CVS"
-    (
-    	set -x
-    	cvs -q up || exit 1
-    ) || exit 1
-    ;;
-*)
-    echo "Checking out a new directory with tag $CVSTAG"
-
-    BUILDDIR=build.d
-    [ -d $BUILDDIR ] && rm -rf $BUILDDIR
-    ROOT=$(cat CVS/Root)
-    REPOS=$(cat CVS/Repository)
-
-    echo "Updating files from CVS"
-    (
-    	set -x
-	cvs -d $ROOT co -r$CVSTAG -d $BUILDDIR $REPOS || exit 1
-    ) || fatal "Can't check out from CVS"
-    [ -z "$RPMDEST" ] && RPMDEST=$(/bin/pwd)
-    cd $BUILDDIR || fatal "Checkout succeeded but no directory"
-    ;;
-esac
-
 if [ $FORCE = yes ]; then
-    echo "Removing files to force rebuild"
+    message "Removing files to force rebuild"
     (
     	set -x
 	/bin/rm -rf config.status config.cache autom4te.cache
@@ -172,7 +179,7 @@ if [ $FORCE = yes ]; then
 fi
 
 if [ ! -f $SPECFILE ]; then
-    echo "Specfile missing, building"
+    message "Specfile missing, building"
     (
     	set -x
 	aclocal
@@ -185,7 +192,7 @@ if [ ! -f $SPECFILE ]; then
 fi
 
 if [ ! -f $TARBALL ]; then
-    echo "Tarball missing, building"
+    message "Tarball missing, building"
     (
     	set -x
 	make dist
@@ -193,12 +200,12 @@ if [ ! -f $TARBALL ]; then
     [ -f $TARBALL ] || fatal "Can't build $TARBALL, giving up"
 fi
 
-echo "Building $RPMDIR directory tree"
+message "Building $RPMDIR directory tree"
 /bin/rm -rf $RPMDIR
 mkdir -p $RPMDIR
 (cd $RPMDIR ; mkdir -p BUILD RPMS/i386 RPMS/`uname -m` SPECS SRPMS )
 
-echo "Building RPMs"
+message "Building RPMs"
 (
     set -x
     $RPMBUILD -bb \
@@ -211,32 +218,32 @@ echo "Building RPMs"
 copyfile ()
 {
     local from=$1
-    local to=$1
+    local to=$2
 
     case "$RPMDEST" in
     "")
-	echo "Moving $from -> $to"
+	message "Moving $from -> $to"
 	mv $from $f2 || exit 1
     	;;
     *:*)
-	echo "Copying $from -> $RPMDEST/$to"
+	message "Copying $from -> $RPMDEST/$to"
 	scp $from $RPMDEST/$to || exit 1
     	;;
     *)
-	echo "Moving $from -> $RPMDEST/$to"
+	message "Moving $from -> $RPMDEST/$to"
 	mv $from $RPMDEST/$to || exit 1
     	;;
     esac
 }
 
 if [ $COPYTARBALL = yes -a ! -z "$RPMDEST" ] ; then
-    echo "Copying tarball to destination"
+    message "Copying tarball to destination"
     copyfile $TARBALL $TARBALL
 fi
 
-echo "Copying RPMs to destination"
+message "Copying RPMs to destination"
 for f in $(find $RPMDIR/RPMS -type f -name \*.rpm) ; do
-    f2=$(echo $(basename $f) | sed -e 's|^\([a-z-]\+-\)|\1'${DISTRO}${DISTRO:+-}'|')
+    f2=$(basename $f | sed -e 's|^\([a-z-]\+-\)|\1'${DISTRO}${DISTRO:+-}'|')
     copyfile $f $f2
 done
 
